# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Xplore' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Xplore
  pod 'Parse'
  pod 'AlamofireImage'

  target 'XploreTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'XploreUITests' do
    # Pods for testing
  end

end
